// Bead 4.2 — View model contracts for the insight cockpit

export interface AcceptanceMetric {
  actionType: string;
  accepted: number;
  rejected: number;
  editedApplied: number;
  deferred: number;
  total: number;
  acceptanceRate: number; // 0..1
}

export interface TimeMetric {
  blockId: string;
  documentId: string;
  secondsSpent: number;
  sessionCount: number;
}

export interface HotspotMetric {
  blockId: string;
  rewriteCount: number;
  avgDeltaMetric: number;
  severity: "low" | "medium" | "high";
}

export interface HelpedVsSlowedResult {
  netSignal: "helped" | "neutral" | "slowed";
  acceptanceRate: number;
  avgTimePerBlock: number;
  hotspotCount: number;
  reasoning: string;
}

export interface InsightsData {
  acceptance: AcceptanceMetric[];
  time: TimeMetric[];
  hotspots: HotspotMetric[];
  helpedVsSlowed: HelpedVsSlowedResult;
}

export interface SessionSummary {
  sessionId: string;
  documentId: string;
  generatedAt: string;
  acceptanceOverview: string;
  timeOverview: string;
  hotspotOverview: string;
  helpedVsSlowed: string;
  markdown: string;
}

/**
 * Compute helped-vs-slowed heuristic from available metrics.
 * Heuristic:
 * - "helped" if acceptanceRate >= 0.5 AND no high-severity hotspots
 * - "slowed" if acceptanceRate < 0.25 OR high-severity hotspot count > 3
 * - "neutral" otherwise
 */
export function computeHelpedVsSlowed(
  acceptance: AcceptanceMetric[],
  hotspots: HotspotMetric[]
): HelpedVsSlowedResult {
  if (acceptance.length === 0) {
    return {
      netSignal: "neutral",
      acceptanceRate: 0,
      avgTimePerBlock: 0,
      hotspotCount: 0,
      reasoning: "No suggestion data yet.",
    };
  }

  const totalSuggestions = acceptance.reduce((s, a) => s + a.total, 0);
  const totalAccepted = acceptance.reduce((s, a) => s + a.accepted + a.editedApplied, 0);
  const acceptanceRate = totalSuggestions > 0 ? totalAccepted / totalSuggestions : 0;
  const highHotspots = hotspots.filter((h) => h.severity === "high").length;

  let netSignal: HelpedVsSlowedResult["netSignal"];
  let reasoning: string;

  if (acceptanceRate >= 0.5 && highHotspots === 0) {
    netSignal = "helped";
    reasoning = `Acceptance rate ${(acceptanceRate * 100).toFixed(0)}% ≥ 50% with no high-friction blocks.`;
  } else if (acceptanceRate < 0.25 || highHotspots > 3) {
    netSignal = "slowed";
    reasoning = `Acceptance rate ${(acceptanceRate * 100).toFixed(0)}% < 25% or ${highHotspots} high-friction blocks detected.`;
  } else {
    netSignal = "neutral";
    reasoning = `Acceptance rate ${(acceptanceRate * 100).toFixed(0)}% with ${highHotspots} high-friction block(s).`;
  }

  return {
    netSignal,
    acceptanceRate,
    avgTimePerBlock: 0,
    hotspotCount: hotspots.length,
    reasoning,
  };
}

/**
 * Generate a session summary markdown document from metric data.
 */
export function generateSessionSummaryMarkdown(
  sessionId: string,
  documentId: string,
  data: InsightsData
): string {
  const { acceptance, time, hotspots, helpedVsSlowed } = data;
  const now = new Date().toISOString();

  const topTime = [...time].sort((a, b) => b.secondsSpent - a.secondsSpent).slice(0, 5);
  const topHotspots = [...hotspots].sort((a, b) => b.rewriteCount - a.rewriteCount).slice(0, 5);

  const signalEmoji = helpedVsSlowed.netSignal === "helped" ? "✅" : helpedVsSlowed.netSignal === "slowed" ? "⚠️" : "➡️";

  return `# Writing Session Summary

- **Session:** ${sessionId}
- **Document:** ${documentId}
- **Generated:** ${now}

---

## Net Signal: ${signalEmoji} ${helpedVsSlowed.netSignal.toUpperCase()}

${helpedVsSlowed.reasoning}

---

## Acceptance by Action Type

${acceptance.length === 0 ? "_No suggestion data._" : acceptance
  .map(
    (a) =>
      `- **${a.actionType}**: ${a.accepted}/${a.total} accepted (${(a.acceptanceRate * 100).toFixed(0)}%) · ${a.rejected} rejected · ${a.editedApplied} edited`
  )
  .join("\n")}

---

## Time by Block (Top ${topTime.length})

${topTime.length === 0 ? "_No time data._" : topTime.map((t) => `- \`${t.blockId.slice(0, 8)}...\`: ${t.secondsSpent.toFixed(0)}s`).join("\n")}

---

## Hotspots (Top ${topHotspots.length})

${topHotspots.length === 0 ? "_No rewrite hotspots._" : topHotspots.map((h) => `- \`${h.blockId.slice(0, 8)}...\`: ${h.rewriteCount} rewrites · avg delta ${(h.avgDeltaMetric * 100).toFixed(0)}% · severity **${h.severity}**`).join("\n")}

---

_Generated by Writing Copilot Cockpit_
`;
}


export interface SearchSuggestionResult {
  suggestionId: string;
  issueSummary: string;
  proposedText: string;
  rank: number;
}

export interface InsightsSummaryTotals {
  suggestions: number;
  accepted: number;
  rejected: number;
  editedApplied: number;
  deferred: number;
  open: number;
  rewrites: number;
}

export interface RecentSuggestionSummary {
  id: string;
  blockId: string;
  actionType: string;
  status: string;
  issueSummary: string;
  proposedText: string;
  selectedText: string;
  createdAt: string;
  decidedAt?: string;
}

export interface RecentRewriteSummary {
  id: string;
  blockId: string;
  deltaMetric: number;
  beforeText: string;
  afterText: string;
  createdAt: string;
}

export interface InsightsSummary {
  filters: {
    documentId?: string;
    sessionId?: string;
    q?: string;
    limit: number;
  };
  totals: InsightsSummaryTotals;
  acceptance: AcceptanceMetric[];
  timeByBlock: TimeMetric[];
  hotspots: HotspotMetric[];
  search: SearchSuggestionResult[];
  recentSuggestions: RecentSuggestionSummary[];
  recentRewrites: RecentRewriteSummary[];
}
